### ISSUE TITLE
カウンターを作ってページ間でカウントの値を共有したい

### ISSUE THREAD

**Issue by yoshidev523** [nobyn0312/jotai_test#1]

**Comment by yoshidev523** [comment]
`_app.tsx` に直接書いちゃってる。これは動かないと思いますね！

<img width="863" alt="image" src="https://github.com/nobyn0312/jotai_test/assets/28664722/6eab9b8c-6b03-4b02-a979-57d25a778a42">

**Comment by yoshidev523** [comment]
_app.tsxはどのページにも共通の設定を行う場所で、ContextのProviderなどを設定したりする場所です。

必ずどこかで `<Component {...pageProps} />` を入れる必要があります。 `pages` 配下の tsxファイルがComponentの中で展開される仕組みです。

https://nextjs.org/docs/pages/building-your-application/routing/custom-app

**Comment by yoshidev523** [comment]
あと、hooksは必ずコンポーネントのトップレベルにて呼び出す必要があります（これはルールです）
画像の赤枠でエラーが出てるのはそれが原因です。

<img width="923" alt="image" src="https://github.com/nobyn0312/jotai_test/assets/28664722/b962eafc-87b9-4f2b-8af4-0ce7b0d41be2">

**Comment by yoshidev523** [comment]
Jotaiは基本的にContext使わないんですね〜 :eyes:
https://qiita.com/al_tarte/items/bfaefc34e9b0be91c72a


global扱いなんだ、なるほど

https://chaika.hatenablog.com/entry/2023/03/11/111100

> jotai の [atom](https://d.hatena.ne.jp/keyword/atom) はデフォルトでは global として扱われる
Provider の中で使用された [atom](https://d.hatena.ne.jp/keyword/atom) は Provider の中で閉じられる
Provider で囲われた[コンポーネント](https://d.hatena.ne.jp/keyword/%A5%B3%A5%F3%A5%DD%A1%BC%A5%CD%A5%F3%A5%C8)から Provider の外の global な [atom](https://d.hatena.ne.jp/keyword/atom) にはアクセスできない
Provider の外の [atom](https://d.hatena.ne.jp/keyword/atom) にアクセスしたい場合は、アクセス可能な [atom](https://d.hatena.ne.jp/keyword/atom) を React の context に store として登録し context 経由でならアクセス可能

**Comment by nobyn0312** [comment]
とりあえず_app.tsxは修正しました。

次にtestpageでもカウンターと値を共有できるようにしたいです
http://localhost:3001/testpage

_app.tsxでproviderを書きました。
storeは必要ないのでしょうか
